{{ if eq .chezmoi.os "linux" -}}

[".fonts/Monaspace"]
    type = "archive"
    url = "https://github.com/githubnext/monaspace/releases/download/v1.400/monaspace-variable-v1.400.zip"
    exact = true
    stripComponents = 1

[".fonts/Window-Fonts"]
    type = "archive"
    url = "https://github.com/binhtran432k/dotfiles/releases/download/archive/Window-Fonts.zip"
    exact = true
    stripComponents = 1

{{- end -}}
