# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    # Force the kernel to bypass the ACPI conflict and use basic pooling
    kernelParams = [ "initcall_blacklist=intel_lpss_init" ];
    # Completely blacklist the buggy Intel Low Power modules
    blacklistedKernelModules = [
      "intel_lpss"
      "intel_lpss_pci"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/78a91100-faa6-4900-96bb-d21a4c7ad028";
    fsType = "btrfs";
    options = [ "subvol=@,compress=zstd,noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/78a91100-faa6-4900-96bb-d21a4c7ad028";
    fsType = "btrfs";
    options = [ "subvol=@home,compress=zstd,noatime" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/78a91100-faa6-4900-96bb-d21a4c7ad028";
    fsType = "btrfs";
    options = [ "subvol=@nix,compress=zstd,noatime" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6FD5-CFF8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/Data" = {
    device = "/dev/disk/by-uuid/8e2f74f9-9dce-4de2-998c-4cc4d7224b58";
    fsType = "ext4";
  };

  swapDevices = [ ];
  zramSwap.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
